---
title: "Assignment 8"
subtitle: "Markov Chain Monte Carlo"
date: 12-01-2023
format: html
editor: visual
---

::: callout-important
# Deadline

**Due date: 11:59pm on Sunday, 10 December 2023.**
:::

::: {.callout-note collapse="true"}
# Invite link for GitHub Classroom

Use the corresponding invite link in [this google doc](https://docs.google.com/document/d/1XTO7obXEr2Yxllxk48wnZ5e49ptPGMsMyl40KEZDGRg/edit?usp=sharing) (accessible with your EPFL account) to accept the assignment. Then go to the [course GitHub organization](https://github.com/MATH-517) and locate the repo titled `ae-6-YOUR_GITHUB_USERNAME` to get started.
:::

::: {.callout-warning collapse="false"}
# Submission requirements

You are required to hand in a PDF version of your report `report.pdf` (generated from the quarto file `report.qmd`) and the quarto file itself. The `report.qmd` should contain all the code necessary to reproduce your results: you should not show the actual code in the PDF report, unless you want to point out something specific.

Your `README.md` should contain instructions on how to reproduce the PDF report from the quarto file. This can be useful if you have issues with the automatic generation of the PDF report right before the deadline.

**Checklist**:

1. [ ] `report.pdf` in GitHub repository (generated from `report.qmd`)
2. [ ] `report.qmd` in GitHub repository (source code, should be able to run from top to bottom)
3. [ ] `README.md` with instructions on how to run the code and reproduce the PDF report
:::

## Problem setting

Since black carbon (BC) is a pollutant known for its adverse health effects, it is of interest to monitor BC mass concentration in urban areas. While stationary measurement devices are able to precisely record BC concentrations (random variable $\mu$), simpler mobile devices provide more flexibility -- at the cost of some measurement noise $\varepsilon$. For a mobile measurement, only $Y = \mu + \varepsilon$ is observed, where we may assume $\varepsilon \sim N(0, \sigma^2)$ with known standard deviation $\sigma = 0.6\, \mu g m^{-3}$ based on lab experiments.

To obtain a detailed overview over the BC concentrations in Lausanne, the aim is to add mobile measurements to those of available stationary devices. We want to predict $\mu$ given a noisy observation $Y=y$ using a Bayesian approach, with stationary measurements motivating a prior Weibull distribution for $\mu$ with shape parameter $2$ and scale parameter $1.2$ (median $\approx 1 \, \mu g m^3$).

## Task

-   Implement a Metropolis--Hastings algorithm for obtaining MCMC samples of $\mu \mid Y=y$ using $N(\tilde{y}, 0.6)$ as *fixed independent proposal distribution for all iterations* (note that this is not a symmetric proposal from the MH perspective!). Here, $\tilde{y}$ is the MAP.

-   Run your algorithm for $y = 0.5$, $y = 1$, and $y = 2$ for illustration. In each run, draw $10000$ samples after a burn-in of $1000$ (less if it takes too long).

-   In this specific scenario, the posterior is in fact analytically available (see the code provided below). Graphically compare the empirical distributions of your MCMC samples with the true posterior densities and the proposal densities for the three considered values of $y$.


:::{.callout-tip}
 It might be wise to compute $\log(\alpha)$ first as a function of the $\log$-densities to avoid numerical issues.
:::

::: {.callout-note appearance="minimal" icon=false collapse=true}
# R code for the posterior density
```r
erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1

dposterior <- function(x, y, scale = 1.2, sd = .6) {
  # x: evaluation points of the density
  # y: observation Y=y (length 1),
  # scale: scale parameter of Weibull prior (shape=2 fixed)
  # sd: standard deviation of Gaussian error (mean=0 fixed)
  a <- 1 / 2 * 1 / sd^2
  c <- 1 / scale^2
  k <- ifelse(x >= 0, x * exp(-a * (x - y)^2 - c * x^2), 0)
  n <- exp(-a * (y^2)) *
    (sqrt(pi) * a * y * exp(a^2 * y^2 / (a + c)) *
      (erf(a * y / sqrt(a + c)) + 1) +
      sqrt(a + c)) / (2 * (a + c)^(3 / 2))
  return(k / n)
}
```
:::

::: {.callout-note appearance="minimal" icon=false collapse=true}

# Python code for the posterior density

```python
from math import pi, sqrt, exp

import numpy as np
from scipy.special import erf


def dposterior(x, y, scale=1.2, sd=0.6):
    """
    analytical posterior density of X given Y=y

    Paramters
    ---------
        x:  Union[float, np.ndarray]
            evaluation points of the density
        y:  float
            observation Y=y
        scale:  float
            scale parameter of Weibull prior (shape=2 fixed)
        sd: float
            standard deviation of Gaussian error (mean=0 fixed)
    """
    a = 1 / (2 * sd**2)
    c = 1 / scale**2

    k = np.where(x >= 0, x * np.exp(-a * (x - y) ** 2 - c * x**2), 0)
    n = (
        np.exp(-a * y**2)
        * (
            sqrt(pi)
            * a
            * y
            * exp(a**2 * y**2 / (a + c))
            * (erf(a * y / sqrt(a + c)) + 1)
            + sqrt(a + c)
        )
        / (2 * (a + c) ** (3 / 2))
    )
    return k / n
```
::: 


::: {.callout-note appearance="minimal" icon=false collapse=true}

# Julia code for the posterior density

```julia
using SpecialFunctions

"""
analytical posterior density of X given Y=y

Paramters
- x:  evaluation points of the density
- y:  observation Y=y
- scale:  scale parameter of Weibull prior (shape=2 fixed)
- sd: standard deviation of Gaussian error (mean=0 fixed)
"""
function dposterior(x, y; scale = 1.2, sd = 0.6)
    a = 1 / (2 * sd^2)
    c = 1 / scale^2

    k = ifelse(x >= 0, x * exp(-a * (x - y)^2 - c * x^2), 0)
    n = exp(-a * y^2) *
        (√(π) * a * y * exp(a^2 * y^2 / (a + c)) *
         (erf(a * y / √(a + c)) + 1) + √(a + c)) /
        (2 * (a + c)^(3 / 2))

    return k / n
end
```
:::


[^1]: less if it takes too long

