---
title: "Assignment 6"
subtitle: "Generating Gaussian samples"
date: 11-10-2023
format: html
editor: visual
bibliography: ref.bib
---

::: callout-important
# Deadline

**Due date: 11:59pm on Sunday, 19 November 2023.**
:::

::: {.callout-note collapse="true"}
# Invite link for GitHub Classroom

Use the corresponding invite link in [this google doc](https://docs.google.com/document/d/1XTO7obXEr2Yxllxk48wnZ5e49ptPGMsMyl40KEZDGRg/edit?usp=sharing) (accessible with your EPFL account) to accept the assignment. Then go to the [course GitHub organization](https://github.com/MATH-517) and locate the repo titled `ae-6-YOUR_GITHUB_USERNAME` to get started.
:::

::: {.callout-warning collapse="false"}
# Submission requirements

You are required to hand in a PDF version of your report `report.pdf` (generated from the quarto file `report.qmd`) and the quarto file itself. The `report.qmd` should contain all the code necessary to reproduce your results: you should not show the actual code in the PDF report, unless you want to point out something specific.

Your `README.md` should contain instructions on how to reproduce the PDF report from the quarto file. This can be useful if you have issues with the automatic generation of the PDF report right before the deadline.

**Checklist**:

1. [ ] `report.pdf` in GitHub repository (generated from `report.qmd`)
2. [ ] `report.qmd` in GitHub repository (source code, should be able to run from top to bottom)
3. [ ] `README.md` with instructions on how to run the code and reproduce the PDF report
:::


# Task

We will study empirically the following methods [^1] for generating from a Gaussian distribution $\mathcal{N}(0,1)$: 

- The inverse transform 
- The Box-Muller transform
- Rejection sampling

We will compare the performance of these methods using the supremum norm
$$
\|f\|_{\infty}:=\sup _{x \in \operatorname{supp}(f)}|f(x)|,
$$

where $f$ is a real-or complex-valued bounded function.

For each of the methods, we will generate $n$ samples and compute the empirical CDF $\hat{F}_n$ of the generated samples. We will then compute the sup-norm between the empirical and theoretical CDFs. More precisely, repeat the following steps $50$ times for each method:

1. Draw a sample of size $n = 10^5$ using the method.
3. Compute the sup-norm between the empirical and theoretical CDFs.

Compare the methods using the sup-norm. [^3]


## Notes on implementation

::: callout-important

For the inverse transform method, you can either use the functions mentionned below or implement it yourself. For the Box-Muller transform and rejection sampling, you will need to implement the methods yourself.

:::

- `R` uses by default the inverse transform in `rnorm()` (see [the source code](https://github.com/r-devel/r-svn/blob/19f9a8f0b3c7659876aac249c851dff93d55e4d9/src/nmath/snorm.c#L265) for other options)
- For `Python`, you can use the code below to generate samples from a standard normal distribution using the inverse transform method:
  
  ::: {.callout-note appearance="minimal" icon=false collapse=false}
  ## Python code for inverse transform sampling

    ```python
        import numpy as np
        from scipy.special import ndtri # quantile function of the standard normal distribution
        x = ndtri(np.random.default_rng().uniform(size=1000))
    ```
  :::

  Note that the default method in `numpy` uses the Ziggurat method [@marsaglia2000ziggurat].

- For `Julia`, the default algorithm for generating random variables is the Ziggurat Method [@marsaglia2000ziggurat]. You can use the code below to generate Gaussian random variables via inverse sampling:

  ::: {.callout-note appearance="minimal" icon=false collapse=false}
  ## Julia code for inverse transform sampling

    ```Julia
    using Distributions
    x = quantile.(Normal(), rand(1000))
    ```
  :::



[^1]: See the [lecture notes](../lectures/08_MonteCarlo.pdf) for more details.
[^2]: The inverse transform method is used by default in `rnorm()`
[^3]: (Optional) You can also compare the methods from a computational point of view by measuring the time it takes to generate the samples.